### ISSUE TITLE
Current git HEAD won't work with pure "grep"

### ISSUE THREAD

**Issue by phmarek** [AndrewRadev/writable_search.vim#10]
If neither `git-grep` nor `ack` are being used, a result list gets displayed (but still called `[No Name]`, with status line `--No lines in buffer--`), but trying to save changes results in `E32: No file name`.

`full_command` gets to be `egrep <pattern> . -R -I -n -H -C3`; the filenames are detected and highlighted; only saving changes won't work.

This is with Debian vim=2:7.4.430-1.

Thanks for any help!

**Comment by AndrewRadev** [comment]
Sorry for taking so long to respond.

This is an odd problem. Seems to work fine for me, and I'm not sure how to debug it. For starters, could you run the `:messages` command and paste the output? It might be that there's an error or warning before that, but it's not seen or something.

**Comment by phmarek** [comment]
Hmmm, with the current 2:7.4.712-3 I can't reproduce either.

Thanks for replying.

**Comment by AndrewRadev** [comment]
I love issues that solve themselves :D. Well, maybe it reallly was a bug with that particular Vim version. Let me know if it happens again.
