### ISSUE TITLE
difference between ags?

### ISSUE THREAD

**Issue by acornejo** [AndrewRadev/writable_search.vim#11]
I was looking for a plugin to do project-wide search and replace and stumbled upon this project (its great!)

Could you comment on what are the differences between this and vim-ags and ctrlsf.vim

**Comment by AndrewRadev** [comment]
Both of these plugins seem nice, and should do the job for you. One thing I see from scrolling through their documentation is that they don't allow adding new lines. I also don't see anything about renaming files. Both are functionalities that writable search has. From what I see in the screenshots, though, both plugins provide nice syntax highlighting, while writable search doesn't.

vim-ags seems to only work with ag, and both writable search and ctrlsf have more backends available. Ctrlsf seems to have a more featureful experience, sort of replacing a quickfix window's functionality (showing a full buffer on the side), which can be both a benefit and a drawback, depends on what you prefer.

In general, I feel like the only way for you to judge, is to try out all of the subject plugins yourself and see which one fits best with your personal workflow.
