### ISSUE TITLE
Can't change "word" to "WORD" ? 

### ISSUE THREAD

**Issue by cs86661** [AndrewRadev/writable_search.vim#12]
I want to change all lowercase word to uppercase, ex. "word" -> "WORD", then the result is nothing changed ?

**Comment by AndrewRadev** [comment]
It might be a problem with comparison while `ignorecase` is set. Do you have `set ignorecase` in your vimrc?

Either way, I've pushed a possible fix. Could you check it out and see if the issue is gone? If not, I'll try digging deeper.

**Comment by cs86661** [comment]
yes! I have `set ignorecase` in vimrc. This issue has been fixed with new patch, thanks!
