### ISSUE TITLE
Broken when running :WriteableSearchFromQuickfix on file with two results?

### ISSUE THREAD

**Issue by jesseleite** [AndrewRadev/writable_search.vim#13]
Firstly, awesome plugin!  I love the `:WriteableSearchFromQuickfix` command, thank you ❤️

Anyway, when running from quickfix, containing a file with two ag results / quickfix entries (like in the `UserController` example below), it doesn't show anything for that file, and the line range is wonky...

```
app/Http/Controllers/UserController.php:115-92
app/Http/Controllers/FormController.php:24-30
      *
      * @return mixed
      */
     public function create()
     {
         $fields = Request::all();
 ```

Thoughts as to what may be happening?

**Comment by AndrewRadev** [comment]
Hm, interesting. Could you give me example files where this happens, so I can replicate it locally? If these are from your work, you could even replace their contents with `?` or something.

> Firstly, awesome plugin! I love the :WriteableSearchFromQuickfix command, thank you

Thank you for the kind words :).

**Comment by jesseleite** [comment]
Sure!  [Here's an example file](https://gist.github.com/jesseleite/7c3d13882968aa43f43488a771b962bd).  In this case I search `func.*Request` and populate both results into the quickfix, then run `:WritableSearchFromQuickfix`.

![2018-11-11 10 00 25](https://user-images.githubusercontent.com/5187394/48314509-ad4b8f00-e598-11e8-974c-ca70cc62f13b.gif)

**Comment by AndrewRadev** [comment]
I think I figured out what the problem is -- the search doesn't output the results in a sorted order -- line 34 before line 19. I've added some logic that sorts things. Could you try it out again?

**Comment by jesseleite** [comment]
Looks like that fixed, thank you! 😊
