### ISSUE TITLE
:WriteableSearchFromQuickfix query pattern param?

### ISSUE THREAD

**Issue by jesseleite** [AndrewRadev/writable_search.vim#14]
Would you be open to an optional `:WriteableSearchFromQuickfix` param?  For example if you passed...

```
:WriteableSearchFromQuickfix 'func.*index'
```

It would open the buffer and immediately highlight anything that matches `func.*index`.

I realize this may not be very useful for users manually running `:WriteableSearchFromQuickfix`.  However, I'm trying to write a function to integrate fzf.vim's `:Ag` (which currently populates quickfix) with your plugin, that will automatically open `:WriteableSearchFromQuickfix` and highlight the search query for the user.

Thoughts?

**Comment by AndrewRadev** [comment]
It's a sensible use case, but it seems very specific. If you're trying to implement it as a sort of automatic callback, would something like this work:

``` vim
exe 'Ag '.search_pattern
WritableSearchFromQuickfix
exe '/'.escape(vimmish_search_pattern, '/')
```

Note that the search pattern would be PCRE, because that's what Ag expects, but Vim would need a translated one. I guess you could try `exe '/\v'.`, but even with `\v`, Vim regex is not quite perl-compatible.

**Comment by jesseleite** [comment]
Yeah I've thought vimmish pattern not being completely compatible with pcre.  Thought [about trying this](https://github.com/othree/eregex.vim), but I'm not sure I want to rely on yet another dependency, and I'm not even sure how accurate it is to pcre anyway.

Regarding your `writable_search#Highlight(query)`, I'll have to dig in.  How does it handle regex queries from ag?  It would be the same vimmish vs pcre problem for highlighting accuracy?

**Comment by AndrewRadev** [comment]
It doesn't, I haven't even tried to do a translation. It's useful when doing a keyword search or something, otherwise it doesn't really match. (It just highlights vim regex matches, basically.)

**Comment by jesseleite** [comment]
Fair enough! Kind of a complex problem either way, but I guess like you said, it’s not necessarily up to your plugin. Thanks!
