### ISSUE TITLE
BufWriteCmd E325 swap file warning when saving `WriteableSearch` buffer if source file is already open

### ISSUE THREAD

**Issue by MartyLake** [AndrewRadev/writable_search.vim#17]
Hello,

Your plugin is amazing and works great. I just have one issue so far, which is: if I modify something in the `WriteableSearch` buffer, and the file it is supposed to modify is already open, when I hit `save`, vim displays a warning E325 `Found a swap file by the name...`.

The error is detected while processing `BufWriteCmd AutoCommands for "<buffer=42>"..function writeable_search#Update[100]..writable_search#proxy#UpdateLocal`

Do you have any idea how to fix this ?
Best,

**Comment by AndrewRadev** [comment]
A swapfile error should be raised if the file is opened in a *different* Vim instance ([`:help E325`](https://vimhelp.org/usr_11.txt.html#E325)). Is that the situation for you? Or are you running `:WritableSearch` in the same Vim as where the buffer is opened?

If you'd like to edit files in one vim instance and open a new one for writable search, I think the only option is to turn off the `swapfile` setting ([`:help 'swapfile'`](https://vimhelp.org/options.txt.html#%27swapfile%27)), but if it's happening in the same Vim, it must be some kind of bug -- I can't replicate it myself if I turn on swapfiles. In that case, it would be useful if I could see your vimrc settings.

**Comment by MartyLake** [comment]
Right, I had some swap files leftover in the files listed in `:WritableSearch`.
I don't know if/how the experience of this plugin could be improved on that regard, I guess now that this issue exist other users might come to it in the future and it is enough.

Thanks for your answer, and creating this plugin!!!

**Comment by AndrewRadev** [comment]
> I don't know if/how the experience of this plugin could be improved on that regard

It would be nice to at least show an informative message, but if I intercept the exception, it would silence the message that Vim already shows. As you say, maybe people will see this issue for more information, at least.

**Comment by MartyLake** [comment]
For the record: iTerm2 session restoration system kept some vim instances alive even if no terminal window was open. Quitting iTerm2 completely closed those phantom vim processes.
