### ISSUE TITLE
Error with git-grep and flags

### ISSUE THREAD

**Issue by phmarek** [AndrewRadev/writable_search.vim#5]
With `git-grep` activated, the command `:WritableSearch -i Operator` gives me a nice, long error message:
```
Searching ...
Error detected while processing function writable_search#Start..writable_search#Parse..writable_search#parser#Run..<SNR>61_BuildProxies:
line    8:
Couldn't parse the filename from: ^@['error: unknown switch ` ''', 'usage: git grep [options] [-e] <pattern> [<rev>...] [[--] <path>...]', ...
```
and so on and on and on.

After that `WriteableSearch` is unusable:
```
Error detected while processing function writable_search#Start..writable_search#Parse:
line    1:
E706: Variable type mismatch for: b:proxies
```

Using the other order `:WritableSearch Operator -i` just says `No results`, which is wrong. (Without `-i` I get matching lines - I tested on this github repo ;)

Thank you for your help!

**Comment by AndrewRadev** [comment]
I'm going to close this issue, since implementing argument/flag parsing would be really, really difficult and probably cause for errors.
